export const CREATE_CARD = "CREATE_CARD";
export const UPDATE_CARD = "UPDATE_CARD";
export const DELETE_CARD = "DELETE_CARD";

export const CREATE_LIST = "CREATE_LIST";
export const UPDATE_LIST_NAME = "UPDATE_LIST_NAME";
export const UPDATE_EDITING_STATUS = "UPDATE_EDITING_STATUS";
export const DELETE_LIST = "DELETE_LIST";
export const ATTACH_TO_LIST = "ATTACH_TO_LIST";
export const DETACH_FROM_LIST = "DETACH_FROM_LIST";

// UI actions
export const UI_ADD_LIST_EDITOR = "UI_ADD_LIST_EDITOR";
export const UI_ADD_CARD_EDITOR = "UI_ADD_CARD_EDITOR";
